#
#
# Copyright 2016 The Symphony Software Foundation
#
# Licensed to The Symphony Software Foundation (SSF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

#before_script: "if [[ \"$TRAVIS_PULL_REQUEST\" = \"false\" ]]; then curl -s https://raw.githubusercontent.com/symphonyoss/contrib-toolbox/master/scripts/download-files.sh | bash ; fi"

language: java
install: true
script:
# Build for PRs
- "if [[ \"$TRAVIS_PULL_REQUEST\" != \"false\" ]]; then mvn clean install && true ; fi"
# Build for master branch
- "if [[ $TRAVIS_BRANCH =~ master && \"$TRAVIS_PULL_REQUEST\" = \"false\" ]]; then mvn clean deploy -Pversioneye --settings settings.xml ; fi"

jdk:
  - oraclejdk8

notifications:
  email:
    recipients:
      - dev-notify@symphony.foundation

env:
  global:
   #Required env for integration testing
   # Need to "gem install travis" first
   # Generated using command "travis encrypt COVERITY_SCAN_TOKEN=blah"
   # - secure: "C4A49ZOQceU/ArLstDxMwn2XSZqvuZW+OA8ZGM0ktGN+yXEXymNYO2c5jgzwXkCzaGrnRTrFH509W1BO003SXkBsLRgC/kYupkPR4sSuWAm575IW8QCrBjWozU42aK4ZUfaFMsW1dQ99LTB6DeyjzWJCG0PKqfU+xjw0v+GJzMBEcj6Es0lHkCk8AjmbuKJkbq06WN/GP+0tVE+AavtGQoWNx34Za7BrY/6sUJkuwevIOc3IkjYN8JCZdKo8QPYDevzg2kBWhI2kX3prau+20uHQjsBqub1sYEuyQ3Ndxj+8ZzJP3M7j4QAcufJMjUxOfFnFLbmvXcj7N2zjVc6/c6z5MW3hoVY2WW+1WGUnoD3lK410SPe+W/eIlJqiYpn10dE7+rcSS4iWCVc8luGXXzgemK/yfgbPAnSWEeHJjKnHdUj6hX3He1Ef4sRjmfXlsd0NuKoshw1IH1mGezZ8yy2shKPmZAvbBaX77bebpd/gfOJE+6i2NbfFyicMJMpruHNbiQ2JQk0QRdFdV569wlmiBzLH/AneyIXWT3/VsMDNL1pAXIl8UCBa2HdQcidINMmHyYD2VDzhEsFrzWGP5EJK1WUo3tecJqor2BpnoWlOxVazZnF3MBAzYcM6ldv/jCYQWAyVSYq/oG/GcipXuwbq0sJHQs5/wIdyetDvFGU="
   # Generated using command "travis encrypt SONAR_LOGIN=blah"
   #- secure: "WdxH3NpGCQ8oIUnr49KFDX1bK3T1ZPcRrgcjo13ekPjskN3AvjkviqX045iPzxw0He9OtbwrPIn27xYddGtb/Q4dAFV5zH5vdCMBuCToicJz8d1svXXjdKoWnrQLGVQ0hTLrWMQff7goN10LRzjuRQQj6u3K1mc21IlWaE3Rn0DNthebqNmPjIXvvCiAwNvaa8EVUiHzz02/wynpJPajeD/Uf2NxjQ4auIqrA5a7jVvJtYv2mJA/HhQBzanJdDxyXJsxlf7DPViBMWxmBpSpNlXiu3nNxkfCkJpiHcLmTIQTw8i8HwSmi9WnS2xyjFAt510HJpACufi5j58yXFRSIDeuxbwsn09LPFB4/L/Gx2laPSbsRe55jG1mQoD58wGTYPX5YusPyDTLM1Nw3rxbHdCd6cxrOkQ4FgotkasLqEa8HmhRu//PqB5M7MUkSLuP65yUHdHn4pdhKR+G9v1uDII5ZDyoidMjlRuL0Ty3PLJdQqyzvh2Wxwc7zECL0ZLeeYdBpAtZYw7S7nyMSituMYQDgsRmT3ISCNLQJor3vMwrtBXaxujS18cox+GsqedtH9hoUZm2Zwoq0MknsTmWOK8n+ey/EFg66tViI1Y24U3PfBT0ZHsviJRRqxpE2ULyVxJNXuesAkoFEsdAVDWjyqQ4E3PrNI8dYq9p2P/tWFQ="
   # Generated using command "travis encrypt VERSIONEYE_API_KEY=blah"
   - secure: "PU2o0PU+oSfuw6BaluMno6uSXgf57Sgd4eimAQ15/1cSAePSWIS2Jpjr3in9tG0kAwhrGhWlZR/nI0o2oo6YEpjsYv3DTaW/AcAnC8AIAQeeDd/5YdZYWxX76ORORF6YuOGcNb7Cz0DkzQosWiRJFHt9/rUGKB9/uaIfh82H8WlfhfxH4BhB9659+XIDV0zF/jTSME2L8Sa/kPb2DuycCviqjS9CMWhCDCz8l7OZpPypvxt3Onk1e14UOpQ50W5+GLpRWiaILei2JuZaxYNs7Ut44MbYZZzkTYUHwFfSdQpK+8u6xbCOkOt/mJ3gASantIJKdWZ97dtwKzgJGKqjDjSvShL5kxj+I4nAe1rtaUv/eUz9/qAp7W6FWfAGVWO6TEqqpn3WAyy7LOYQrlYLgrumfgfZv2o3T+8oaiLJnHDmnVepboeL77aaTzAQskkUXUeFFGwFEn06veqgcP3oGfLuF1+yOIJApm5el4lkztwzu5iyCO9gQLYw9mVmAPq5grctpxpKGNfGuBEDp7oaWoZh3je5/FsT9mYbCkQiehHxuvEFSWMNUxHz+nSwrx1YY5pjvIRHb5+hIivWMAax7lxxDxSi26btlPJt9+xYo5bOxo0Ou6CaVVLbPsNwHhdmdU9NFP41Ov8lX1qRPcybxHO2Mv8QiCcPhEyoHe1x9y8="

addons:
  coverity_scan:
    project:
      name: "symphonyoss/symphony-java-api"
      description: "Build submitted via Travis CI"
    notification_email: dev-notify@symphony.foundation
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile install"
    branch_pattern: $COVERITY_BRANCH_PATTERN
